<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD2n8Wpy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD2n8Wpy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD2n8Wpy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD2n8Wpy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD2n8Wpy\App_KernelDevDebugContainer([
    'container.build_hash' => 'D2n8Wpy',
    'container.build_id' => 'c77cf484',
    'container.build_time' => 1679135256,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD2n8Wpy');
