<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCU7xmvl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCU7xmvl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCU7xmvl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCU7xmvl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCU7xmvl\App_KernelDevDebugContainer([
    'container.build_hash' => 'CU7xmvl',
    'container.build_id' => 'dfd5e19e',
    'container.build_time' => 1679698010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCU7xmvl');
