<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_da-22ca24.js',
                '/build/app.js',
            ],
        ],
        'method2' => [
            'js' => [
                '/build/runtime.js',
                '/build/method2.js',
            ],
        ],
    ],
],

]];
